# Generated by Django 3.0.5 on 2020-04-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readmybook', '0002_auto_20200414_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksdb',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('notavailable', 'notavailable')], default='available', max_length=20),
        ),
    ]
