# Generated by Django 3.0.5 on 2020-04-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readmybook', '0003_booksdb_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestbook',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('received', 'received'), ('returned', 'returned'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='pending', max_length=20),
        ),
    ]
